// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVEaFA3YNcreKPMpHPL12fluLaVdZzp7U',
    appId: '1:337909267770:web:9ea46c9ba0dd745ae4a403',
    messagingSenderId: '337909267770',
    projectId: 'nightlife-app-9a7f1',
    authDomain: 'nightlife-app-9a7f1.firebaseapp.com',
    storageBucket: 'nightlife-app-9a7f1.firebasestorage.app',
    measurementId: 'G-LBH1Q372T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbNwIo_Z9Xo0kLe3BE7ieAAKTFWInCwsI',
    appId: '1:954804179384:android:8534cfa4a7b4abe0f2bf4d',
    messagingSenderId: '954804179384',
    projectId: 'hii-app-aa0f1',
    storageBucket: 'hii-app-aa0f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFKJcmqvIttHNsyvPk_gAq_wU41tf-II',
    appId: '1:954804179384:ios:b6d1e2d0734e8951f2bf4d',
    messagingSenderId: '954804179384',
    projectId: 'hii-app-aa0f1',
    storageBucket: 'hii-app-aa0f1.firebasestorage.app',
    iosClientId: '954804179384-a3rvu5o7b5c05gjhepdnmfsfai7k0h34.apps.googleusercontent.com',
    iosBundleId: 'com.davisantony.nightlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEI31JBYsYDZ_ilwQhiD8QMIrDrAd9Fds',
    appId: '1:337909267770:ios:6e3ac9e4d704510ee4a403',
    messagingSenderId: '337909267770',
    projectId: 'nightlife-app-9a7f1',
    storageBucket: 'nightlife-app-9a7f1.firebasestorage.app',
    iosBundleId: 'com.davisantony.nightlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVEaFA3YNcreKPMpHPL12fluLaVdZzp7U',
    appId: '1:337909267770:web:595cbbedefeb581ae4a403',
    messagingSenderId: '337909267770',
    projectId: 'nightlife-app-9a7f1',
    authDomain: 'nightlife-app-9a7f1.firebaseapp.com',
    storageBucket: 'nightlife-app-9a7f1.firebasestorage.app',
    measurementId: 'G-ECVEZ0X840',
  );

}